import ContainerColumns from '@/components/Container/ContainerColumns/ContainerColumns';
import Layout from '@/layout/Layout';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout classes="bg-gray-100" hasSpacing>
        <div className="custom-container mx-auto">
          <ContainerColumns classes="gap-4">
            <aside className="custom-container-cols-left border rounded">
              <h1>Navbar</h1>
            </aside>
            <section className="border rounded">
              <h1>Main</h1>
            </section>
            <aside className="custom-container-cols-right border rounded">
              <h1>Info</h1>
            </aside>
          </ContainerColumns>
        </div>
      </Layout>
    </>
  );
}
